### ISSUE TITLE
S2CellId.id() cant be represented by Number

### ISSUE THREAD

**Issue by Niels-Be** [billyriantono/s2cellid-node#1]
Calling `S2CellId.id()` results in truncated numbers since CellIds are `uint64` and Node represents this as Double. 

To fix this I would recommend to return the id as a array of two `uint32`: `[hi, lo]`.
e.g. `toHiLoId()`. 
Implementation would be something like:

```
uint64_t id = obj.this_->id();
uint32_t lo = (uint32_t)(id);
uint32_t hi = (uint32_t)(id >> 32);
set return value as array [hi, lo]
```

Alternative just return the Id as String, so other libraries can parse the string.

**Comment by billyriantono** [comment]
Ok i will take look for this... Thanks for your helps !

**Comment by Niels-Be** [comment]
String implementation:

```
void CellId::IdString(const FunctionCallbackInfo<Value>& args) {
    Isolate* isolate = args.GetIsolate();
    CellId* obj = node::ObjectWrap::Unwrap<CellId>(args.Holder());
    args.GetReturnValue().Set(String::NewFromUtf8(isolate, std::to_string(obj->this_.id()).c_str()));
}
```

**Comment by billyriantono** [comment]
oke i will add this function Thanks !

**Comment by billyriantono** [comment]
added ... Thanks @WaeCo
