### ISSUE TITLE
Installation problem Windows version 1.3.1

### ISSUE THREAD

**Issue by klisman** [billyriantono/s2cellid-node#12]
Can't install in windows 10.
https://gist.github.com/klisman/866855fb847d195d312177cbeb2b61ab

**Comment by billyriantono** [comment]
What is your node version ? Visual C++ compiler installed ?

**Comment by klisman** [comment]
Node v4.4.5
I have all these redist http://image.prntscr.com/image/d90b960a8f52424693932b918ba443f6.png

**Comment by billyriantono** [comment]
Have python 2.7 installed ? :Ad

**Comment by klisman** [comment]
Yes, I repair, just to check, but it is not the problem.
Python PATH is correct.
I think I will install a linux.
Thanks

**Comment by cypherix93** [comment]
Can you try installing Visual Studio 2015 Update 2 or 3? Or try installing this: http://landinghub.visualstudio.com/visual-cpp-build-tools

**Comment by klisman** [comment]
The problem persists, Visual Studio 2015 Update 3

**Comment by cypherix93** [comment]
Could you upload the new npm-debug.log after installing VS 2015 Update 3?

@billyriantono Can we make sure this compiles on Node 4.x? On my end there are no errors compiling on Node 6.x.

**Comment by klisman** [comment]
@cypherix93 is you running fine in Windows 10?
Is probably my PC.

npm-debug.log
https://gist.github.com/klisman/cf1e7d306cd44913489b742e73338e35

**Comment by cypherix93** [comment]
I am currently on Windows 7. I haven't made the move to Windows 10 yet (probably won't anytime soon) so I currently don't have a Windows 10 machine to test this on. :/

Unfortunately, the npm-debug.log doesn't provide any information on where the build is failing. Would it be too much to ask to try it on Node 6.x? Maybe if you are not willing to update entirely, could you try in a test machine?

**Comment by st0ffern** [comment]
It is working on windows 10.

@klisman go to
- your settings
- apps
- select Visual Studio.
- change
- and make shure you have installed:
- Common Tools for Visual C++

if you dont have this it does not work..

**Comment by klisman** [comment]
Solved
Node V6.x.x
Last version of npm - npm install -g npm@next
Common Tools for Visual C++
