### ISSUE TITLE
Failed at the s2geometry-node@1.3.1 install script 'node-gyp rebuild'.

### ISSUE THREAD

**Issue by necm1** [billyriantono/s2cellid-node#14]
Hello!
I'm trying to install pokemon-go-api (https://github.com/Armax/Pokemon-GO-node-api) and getting this error.

> C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(356,5): error MSB6006: "CL.exe" wurd
> e mit dem Code 5 beendet. [C:\Users\Frenk\Desktop\server\node_modules\pokemon-go-api\node_modules\s2geometry-node\build
> \NativeExtension.vcxproj]
> gyp ERR! build error
> gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
> gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
> gyp ERR! stack     at emitTwo (events.js:87:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
> gyp ERR! System Windows_NT 10.0.10586
>  ERR! command "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
> gyp ERR! cwd C:\Users\Frenk\Desktop\server\node_modules\pokemon-go-api\node_modules\s2geometry-node
> gyp ERR! node -v v4.4.5
> gyp ERR! node-gyp -v v3.3.1
> gyp ERR! not ok
> npm ERR! Windows_NT 10.0.10586
> npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "pokemon-go-api"
> npm ERR! node v4.4.5
> npm ERR! npm  v2.15.5
> npm ERR! code ELIFECYCLE
> 
> npm ERR! s2geometry-node@1.3.1 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the s2geometry-node@1.3.1 install script 'node-gyp rebuild'.
> npm ERR! This is most likely a problem with the s2geometry-node package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node-gyp rebuild
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs s2geometry-node
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!
> npm ERR!     npm owner ls s2geometry-node
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     C:\Users\Frenk\Desktop\server\npm-debug.log

Would be awesome, if you can fix it. :+1: 
Regards

**Comment by billyriantono** [comment]
have try npm install -g npm@next ?

**Comment by necm1** [comment]
@billyriantono I'm still getting this now (I changed Visual Studio and added Common Tools for Visual C++):

> C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.c(34): error C2373: "__pfnDliNot
> ifyHook2": Neudefinition; unterschiedliche Modifizierer [C:\Users\Frenk\AppData\Roaming\npm\node_modules\s2geometry-nod
> e\build\NativeExtension.vcxproj]
>   C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\delayimp.h(134): note: Siehe Deklaration von "__pfnDli
>   NotifyHook2"
> gyp ERR! build error
> gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
> gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
> gyp ERR! stack     at emitTwo (events.js:87:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
> gyp ERR! System Windows_NT 10.0.10586
> gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
> gyp ERR! cwd C:\Users\Frenk\AppData\Roaming\npm\node_modules\s2geometry-node
> gyp ERR! node -v v4.4.5
> gyp ERR! node-gyp -v v3.3.1
> gyp ERR! not ok
> C:\Users\Frenk\AppData\Roaming\npm\npm -> C:\Users\Frenk\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
> npm ERR! Windows_NT 10.0.10586
> npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "s2geometry-node" "-g" "npm@next"
> npm ERR! node v4.4.5
> npm ERR! npm  v2.15.5
> npm ERR! code ELIFECYCLE
> 
> npm ERR! s2geometry-node@1.3.1 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the s2geometry-node@1.3.1 install script 'node-gyp rebuild'.
> npm ERR! This is most likely a problem with the s2geometry-node package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node-gyp rebuild
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs s2geometry-node
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!
> npm ERR!     npm owner ls s2geometry-node
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     C:\Users\Frenk\Desktop\server\npm-debug.log

**Comment by kvcpr** [comment]
Try to install node-gyp
`npm install -g node-gyp`

**Comment by necm1** [comment]
working now. Thanks @kacepe & @billyriantono
