### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by raz3r** [billyriantono/s2cellid-node#16]
I can't seem to find a way to install this library on Windows 10. I have Visual C++ Build Tools already installed. Tried `npm install -g npm@next`, tried `npm install -g node-gyp`. Still the same error as below:

`MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.`

**Comment by billyriantono** [comment]
You have install python 2.7 ? And Net framework?

**Comment by raz3r** [comment]
Nevermind, solved :)
