### ISSUE TITLE
Provide a link to nodes2ts within the readm

### ISSUE THREAD

**Issue by vekexasia** [billyriantono/s2cellid-node#21]
Helllo @billyriantono 

first of all thank you for your efforts in bringing s2 geometry to node. Since I needed to use S2 within the browser I took the time to re-write everything in vanilla js (well actually it's in Typescript and then transpiled to vanilla js).

Would you take the time to reference `nodes2ts` as alternative to your library instead of `s2-geometry-javascript` ?

**Comment by billyriantono** [comment]
done ! 🎯
