### ISSUE TITLE
Install Failed node-gyp rebuild

### ISSUE THREAD

**Issue by ButchMonkey** [billyriantono/s2cellid-node#4]
Failed at the s2geometry-node@1.2.2 install script 'node-gyp rebuild'.

failed when running "npm install s2geometry-node" or by building locally

Any Ideas? 
thanks

```
npm ERR! node v0.12.0
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE

npm ERR! s2geometry-node@1.2.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the s2geometry-node@1.2.2 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the s2geometry-node package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs s2geometry-node
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls s2geometry-node
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\nodejs\npm-debug.log
```

[npm-debug.txt](https://github.com/billyriantono/s2geometry-node/files/378077/npm-debug.txt)

**Comment by st0ffern** [comment]
same here.
getting lots of: 
`error C2065: 'M_PI_2': undeclared identifier (compiling source file . .\geometry\s2polyline.cc`

**Comment by NideoTV** [comment]
Same here :( So much of :

c:\users\nicolas\documents\poketest\node_modules\s2geometry-node\geometry\s1ang
le.h(58): error C2065: 'M_PI': undeclared identifier (compiling source file ..\
src\NativeExtension.cc) [C:\Users\Nicolas\Documents\poketest\node_modules\s2geo
metry-node\build\NativeExtension.vcxproj]

**Comment by billyriantono** [comment]
for windows user please wait till @cypherix93 verify and make a PR from his fork .. Thanks

**Comment by billyriantono** [comment]
updated on
