### ISSUE TITLE
Installation on windows

### ISSUE THREAD

**Issue by st0ffern** [billyriantono/s2cellid-node#5]
Hi,

I have tried to install with both Nodejs v6 and v4
i get the same error:

```
419 info install s2geometry-node@1.2.3
420 verbose unsafe-perm in lifecycle true
421 info s2geometry-node@1.2.3 Failed to exec install script
422 verbose unlock done using C:\Users\Kristoffer\AppData\Roaming\npm-cache\_locks\s2geometry-node-403f084db7e331da.lock for D:\dev\node_modules\s2geometry-node
423 verbose stack Error: s2geometry-node@1.2.3 install: `node-gyp rebuild`
23 verbose stack Exit status 1
423 verbose stack     at EventEmitter.<anonymous> (C:\Users\Kristoffer\AppData\Roaming\nvm\v4.4.7\node_modules\npm\lib\utils\lifecycle.js:217:16)
423 verbose stack     at emitTwo (events.js:87:13)
423 verbose stack     at EventEmitter.emit (events.js:172:7)
423 verbose stack     at ChildProcess.<anonymous> (C:\Users\Kristoffer\AppData\Roaming\nvm\v4.4.7\node_modules\npm\lib\utils\spawn.js:24:14)
423 verbose stack     at emitTwo (events.js:87:13)
423 verbose stack     at ChildProcess.emit (events.js:172:7)
423 verbose stack     at maybeClose (internal/child_process.js:827:16)
423 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
424 verbose pkgid s2geometry-node@1.2.3
425 verbose cwd D:\dev\test
426 error Windows_NT 10.0.10586
427 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "-S" "s2geometry-node"
428 error node v4.4.7
429 error npm  v2.15.8
430 error code ELIFECYCLE
431 error s2geometry-node@1.2.3 install: `node-gyp rebuild`
431 error Exit status 1
432 error Failed at the s2geometry-node@1.2.3 install script 'node-gyp rebuild'.
432 error This is most likely a problem with the s2geometry-node package,
432 error not with npm itself.
432 error Tell the author that this fails on your system:
432 error     node-gyp rebuild
432 error You can get information on how to open an issue for this project with:
432 error     npm bugs s2geometry-node
432 error Or if that isn't available, you can get their info via:
432 error
432 error     npm owner ls s2geometry-node
432 error There is likely additional logging output above.
433 verbose exit [ 1, true ]
434 verbose unbuild node_modules\s2geometry-node
435 info preuninstall s2geometry-node@1.2.3
436 info uninstall s2geometry-node@1.2.3
437 verbose unbuild rmStuff s2geometry-node@1.2.3 from D:\dev\node_modules
```

cc @billyriantono  any ideas?

**Comment by cypherix93** [comment]
@billyriantono said he didn't configure his node-gyp to build on Windows yet. Last I checked, he said he's working on it. See if it works on a Linux machine (maybe setup a VM).

**Comment by st0ffern** [comment]
I will also look into it..

**Comment by cypherix93** [comment]
I tried diving into the library. There are ways to get rid of a bunch of the errors like `M_PI: undeclared identifier`. But I figured I should wait for his take on it.

Edit: I'll ask him if he wants PRs.

**Comment by st0ffern** [comment]
@cypherix93
PR`s are always good. They speed up all prosesses.
If he dont want a PR he can just cancel the request.

I suggest you create a PR :)

**Comment by billyriantono** [comment]
@cypherix93 very welcome for PR :)

**Comment by st0ffern** [comment]
cc @billyriantono  i located the error i think:

```
fatal error C1083: Cannot open include file: 'strings.h': No such file or directory (compiling
source file ..\viewfinder\viewfinder.cc)
```

**Comment by w0bbes** [comment]
Hey @billyriantono, thanks for the hard work.

Same issues here, trying to compile on windows. Any eta?

**Comment by billyriantono** [comment]
not yet any eta... because i don't have windows machine so i need to do this on my office .. :) and after look the error maybe it's need many changes to make compatible.. but do you have try this workaround ? https://github.com/nodejs/node-gyp/issues/629#issuecomment-153196245

**Comment by cypherix93** [comment]
Hey guys, I have just made PR #6 which solves _most_ of the issues with compiling on Windows. Please check to see if you can solve the rest.

**Comment by jimdubbs** [comment]
I tried installing after this PR and I still get this error:

C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\src\win_delay_lo
ad_hook.c(34): error C2373: '__pfnDliNotifyHook2': redefinition; different type
 modifiers [C:\github\Pokemon-GO-node-api\node_modules\s2geometry-node\build\Na
tiveExtension.vcxproj]

  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\delayimp.h(134
  ): note: see declaration of '__pfnDliNotifyHook2'

Unfortunately im not sure about how to go about fixing this.

**Comment by cypherix93** [comment]
@jimdubbs Could you try pulling #10? That was the finalized branch that got merged today.

**Comment by billyriantono** [comment]
npm install -g npm@next or try using latest npm

**Comment by jimdubbs** [comment]
Updating to the latest npm solved this, thank you!
