### ISSUE TITLE
react native

### ISSUE THREAD

**Issue by dotomaz** [billyriantono/s2cellid-node#8]
I would like to use this in ReactNative app. How hard would it be to port the lib to react native component?

**Comment by st0ffern** [comment]
@dotomaz you should know that if you wanna create a pokemon app, then you are going to court an jail..
Did you read the terms?

> ARBITRATION NOTICE: EXCEPT IF YOU OPT OUT AND EXCEPT FOR CERTAIN TYPES OF DISPUTES DESCRIBED IN THE “AGREEMENT TO ARBITRATE” SECTION BELOW, YOU AGREE THAT DISPUTES BETWEEN YOU AND NIANTIC WILL BE RESOLVED BY BINDING, INDIVIDUAL ARBITRATION, AND YOU ARE WAIVING YOUR RIGHT TO A TRIAL BY JURY OR TO PARTICIPATE AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS ACTION OR REPRESENTATIVE PROCEEDING

there are more.. :smile:

**Comment by dotomaz** [comment]
Sure I always read the TOS :)
