### ISSUE TITLE
S2LatLng returns bad lat, lng

### ISSUE THREAD

**Issue by kvcpr** [billyriantono/s2cellid-node#9]
For

``` javascript
var latlng = new s2.S2LatLng(44.0378862, 10.0458712)
console.log(latlng.normalized().lat);
```

Console output:
`4.1776780476742336e-302`

I'm trying also with radians as parameters, but this same issue. 

``` javascript
function toRad(Value) {
    return Value * Math.PI / 180;
}
var latlng = new s2.S2LatLng(toRad(44.0378862), toRad(10.0458712)).normalized().lat;
console.log(latlng);
```

Console output:
`4.1777458623119393e-302`

**Comment by waryas** [comment]
Can confirm, any news regarding this issue? Happens on both linux / windows oses.
Just try the example or the code above.

**Comment by billyriantono** [comment]
i think that because Number in NodeJS can't handle that ..

**Comment by kingsonc** [comment]
Is there a workaround for this at the moment?
